plugins:
  - "experiment_training.components.dataloader.lerobot_data"
  - "experiment_training.components.loss.sinkhorn_knopp"
  - "experiment_training.components.optimizer.adamw_cosine_decay"
  - "experiment_training.components.trainer.imitation_learning.variational_flow_matching_policy.variational_flow_matching_policy_trainer"
model:
  find_unused_parameters: true
  component_config_paths:
    backbone: "experiment_models/variational_flow_matching_policy/exp1/backbone.yaml"
    left_hand_extractor: "experiment_models/variational_flow_matching_policy/exp1/left_hand_extractor.yaml"
    right_hand_extractor: "experiment_models/variational_flow_matching_policy/exp1/right_hand_extractor.yaml"
    da3: "experiment_models/variational_flow_matching_policy/exp1/da3.yaml"
    vqvae_posterior: "experiment_models/variational_flow_matching_policy/exp1/vqvae_posterior.yaml"
    vqvae_prior: "experiment_models/variational_flow_matching_policy/exp1/vqvae_prior.yaml"
    info_embedder: "experiment_models/variational_flow_matching_policy/exp1/info_embedder.yaml"
    gate: "experiment_models/variational_flow_matching_policy/exp1/gate.yaml"
    moe_action_decoder: "experiment_models/variational_flow_matching_policy/exp1/moe_action_decoder.yaml"
    
  component_build_args:
    backbone:
      init: false
      freeze: false
    left_hand_extractor:
      init: false
      freeze: false
    right_hand_extractor:
      init: false
      freeze: false
    da3:
      init: false
      freeze: true
    vqvae_posterior:
      init: true
      freeze: false
    vqvae_prior:
      init: true
      freeze: false
    info_embedder:
      init: true
      freeze: false
    gate:
      init: true
      freeze: false
    moe_action_decoder:
      init: true
      freeze: false
  component_optims:
    backbone:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.999]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    left_hand_extractor:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    right_hand_extractor:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    vqvae_posterior:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    vqvae_prior:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    info_embedder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    gate:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1
    moe_action_decoder:
      type: "adamw_warmup_cosine_decay"
      params:
        lr: 1.0e-4 # AdamW
        betas: [0.9, 0.995]
        eps: 1.0e-10
        weight_decay: 0.0001
        max_lr: 2.0e-4 # OneCycleLR
        total_steps: 130000
        epochs: null
        steps_per_epoch: null
        pct_start: 0.03
        warmup_strategy: 'linear'
        div_factor: 1300
        final_div_factor: 200.0
        alpha: null
        exponent: 1.0
        last_epoch: -1


data:
  datamodule:
    type: "lerobot_dataset_factory"
    params:
      task_name: 'picknplace'
      local_files_only: false
      root: '.'
      repo_id: 'joon001001/igris-b-pnp_v3.3.2'
      action_horizon: 40
      obs_proprio_history: 40
      obs_images_history: 1
      HZ: 20
  batch_size: 32
  num_workers: 12
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 1
train:
  project_name: 'vfp_adamw_cosine_decay_v3.3.2_unfreeze_backbone'
  epoch: 1000
  load_dir: null
  save_every: 3
  save_dir: "experiment_training/imitation_learning/variational_flow_matching_policy/exp2"
  trainer: 
    type: 'variational_flow_matching_policy_trainer'
  loss:
    type: "sinkhorn_knopp"
    params:
      p: 1
      lam_state: 0.2
      blur: 0.004
      debias: True       
      backend: "auto"
      scaling: 0.5