plugins:
  - "experiment_training.imitation_learning.dataloader.lerobot_data"
  - "experiment_training.imitation_learning.loss.l2"
  - "experiment_training.imitation_learning.optimizer.schedule_free_radam"
  - "experiment_training.imitation_learning.trainer.cfg_vqvae_flow_matching_trainer"
model:
  find_unused_parameters: true
  component_config_paths:
    backbone: "experiment_models/cfg_vqvae_flow_matching/exp1/backbone.yaml"
    vqvae_posterior: "experiment_models/cfg_vqvae_flow_matching/exp1/vqvae_posterior.yaml"
    vqvae_prior: "experiment_models/cfg_vqvae_flow_matching/exp1/vqvae_prior.yaml"
    vqvae_codebook: "experiment_models/cfg_vqvae_flow_matching/exp1/vqvae_codebook.yaml"
    info_encoder: "experiment_models/cfg_vqvae_flow_matching/exp1/info_encoder.yaml"
    action_decoder: "experiment_models/cfg_vqvae_flow_matching/exp1/action_decoder.yaml"
  component_optims:
    backbone:
      type: "schedule_free_radam"
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        silent_sgd_phase: true
    vqvae_posterior:
      type: "schedule_free_radam"
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        silent_sgd_phase: true
    vqvae_prior:
      type: "schedule_free_radam"
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        silent_sgd_phase: true
    vqvae_codebook:
      type: "schedule_free_radam"
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        silent_sgd_phase: true
    info_encoder:
      type: "schedule_free_radam"
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        silent_sgd_phase: true
    action_decoder:
      type: "schedule_free_radam"
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        silent_sgd_phase: true


data:
  datamodule:
    type: "lerobot_dataset_factory"
    params:
      task_name: 'picknplace'
      local_files_only: true
      root: '~/igris-b-pnp/lerobot_dataset/data'
      repo_id: 'joon001001/igris-b-pnp-lerobot'
      action_horizon: 40
      obs_proprio_history: 40
      obs_images_history: 1
      HZ: 20
  batch_size: 224
  num_workers: 12
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 1
train:
  project_name: 'cfg_vqvae_flow_matching exp1'
  epoch: 1000
  load_dir: null
  save_every: 10
  save_dir: "~/offline_trainer/experiment_training/imitation_learning/cfg_vqvae_flow_matching/exp1"
  trainer: 
    type: 'cfg_vqvae_flow_matching_trainer'
  loss:
    type: "l2_loss"
    params:
      reduction: "sum"
